server:
  port: 9090
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/rongxiaotong?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123789456

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

